#!/bin/sh

set -e
while [ $# -gt 0 ]; do
    arg="$1"
    case "$arg" in
	-t)
	    arch="$2"
	    shift
	    ;;
	-u)
	    mirror="$2"
	    shift
	    ;;
	-v)
	    livemirror="$2"
	    shift
	    ;;
	-w)
	    cache="$2"
	    shift
	    ;;
	--)
	    ;;
	*)
	    temp="$temp "'"'"$arg"'"'
	    ;;
    esac
    shift
done

lb_opts=""

case "$arch" in
    amd64)
	lb_opts="$lb_opts --debian-installer live --architectures amd64"
	;;
    i386)
	lb_opts="$lb_opts --debian-installer live --architectures i386 --linux-flavours 686-pae"
	;;
esac

#echo "using $cache" >&2
#cache="http://192.168.10.43:3142"
FTP_PROX="\"$cache/\""
HTTP_PROX="\"$cache/\""
MI_CHROOT="\"$cache/$livemirror\""
MI_CHROOTS="\"$cache/securitydebian.org/debian\""
MI_PAR="\"$cache/$livemirror\""
MI_BI="\"http://$mirror\""


lb config noauto \
   --bootappend-live "boot=live components locales=de_DE.UTF-8 keyboard-layouts=de username=brew" \
   --memtest memtest86 \
   --iso-application "BREWLinux" \
   --iso-publisher "BREW c00clupea" \
   --iso-volume "brew live" \
   --apt-ftp-proxy  $FTP_PROX \
   --apt-http-proxy $HTTP_PROX \
    --mirror-binary $MI_BI \
    --mirror-binary-security "http://security.debian.org/" \
    --mirror-bootstrap $MI_BI \
    --mirror-chroot  $MI_CHROOT \
    --mirror-chroot-security $MI_CHROOT \
    --parent-mirror-bootstrap $MI_PAR \
     $lb_opts 
     "${@}"

